---
- hosts: app_servers
  serial: 1
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: AgileBPA PoC Container
      docker:
        image: akiratech/rfq993471
        state: reloaded
        pull: always
        ports: 3000:3000
        count: 2
        command: sleep 1d
